apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: swj3elsr9-java-springboot
  janus-idp.io/tekton: swj3elsr9-java-springboot
  backstage.io/kubernetes-id: swj3elsr9-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: swj3elsr9-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
